apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csagent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <GIT_REPO_URL>
    targetRevision: main
    path: deploy/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: csagent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
