apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: csagent
  namespace: csagent
spec:
  selector:
    matchLabels:
      app: csagent-backend
  endpoints:
    - port: http
      path: /api/metrics
      interval: 15s
