apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csagent-data
  namespace: csagent
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
  storageClassName: alicloud-disk-essd
